// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	domain "avitoBooking/internal/core/domain"
	context "context"

	uuid "github.com/google/uuid"
	mock "github.com/stretchr/testify/mock"
)

// bookService is an autogenerated mock type for the bookService type
type bookService struct {
	mock.Mock
}

// CancelUserBooking provides a mock function with given fields: ctx, userId, bookingId
func (_m *bookService) CancelUserBooking(ctx context.Context, userId uuid.UUID, bookingId string) (domain.BookingRequest, error) {
	ret := _m.Called(ctx, userId, bookingId)

	if len(ret) == 0 {
		panic("no return value specified for CancelUserBooking")
	}

	var r0 domain.BookingRequest
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, string) (domain.BookingRequest, error)); ok {
		return rf(ctx, userId, bookingId)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, string) domain.BookingRequest); ok {
		r0 = rf(ctx, userId, bookingId)
	} else {
		r0 = ret.Get(0).(domain.BookingRequest)
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID, string) error); ok {
		r1 = rf(ctx, userId, bookingId)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// CreateBooking provides a mock function with given fields: ctx, booking
func (_m *bookService) CreateBooking(ctx context.Context, booking domain.BookingRequest) (domain.BookingRequest, error) {
	ret := _m.Called(ctx, booking)

	if len(ret) == 0 {
		panic("no return value specified for CreateBooking")
	}

	var r0 domain.BookingRequest
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, domain.BookingRequest) (domain.BookingRequest, error)); ok {
		return rf(ctx, booking)
	}
	if rf, ok := ret.Get(0).(func(context.Context, domain.BookingRequest) domain.BookingRequest); ok {
		r0 = rf(ctx, booking)
	} else {
		r0 = ret.Get(0).(domain.BookingRequest)
	}

	if rf, ok := ret.Get(1).(func(context.Context, domain.BookingRequest) error); ok {
		r1 = rf(ctx, booking)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetBookings provides a mock function with given fields: ctx, pagination
func (_m *bookService) GetBookings(ctx context.Context, pagination domain.Pagination) ([]domain.BookingRequest, int, error) {
	ret := _m.Called(ctx, pagination)

	if len(ret) == 0 {
		panic("no return value specified for GetBookings")
	}

	var r0 []domain.BookingRequest
	var r1 int
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, domain.Pagination) ([]domain.BookingRequest, int, error)); ok {
		return rf(ctx, pagination)
	}
	if rf, ok := ret.Get(0).(func(context.Context, domain.Pagination) []domain.BookingRequest); ok {
		r0 = rf(ctx, pagination)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.BookingRequest)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, domain.Pagination) int); ok {
		r1 = rf(ctx, pagination)
	} else {
		r1 = ret.Get(1).(int)
	}

	if rf, ok := ret.Get(2).(func(context.Context, domain.Pagination) error); ok {
		r2 = rf(ctx, pagination)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// GetMyBookings provides a mock function with given fields: ctx, userId
func (_m *bookService) GetMyBookings(ctx context.Context, userId uuid.UUID) ([]domain.BookingRequest, error) {
	ret := _m.Called(ctx, userId)

	if len(ret) == 0 {
		panic("no return value specified for GetMyBookings")
	}

	var r0 []domain.BookingRequest
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) ([]domain.BookingRequest, error)); ok {
		return rf(ctx, userId)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) []domain.BookingRequest); ok {
		r0 = rf(ctx, userId)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.BookingRequest)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, userId)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// newBookService creates a new instance of bookService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newBookService(t interface {
	mock.TestingT
	Cleanup(func())
}) *bookService {
	mock := &bookService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
