// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	domain "avitoBooking/internal/core/domain"
	context "context"

	uuid "github.com/google/uuid"
	mock "github.com/stretchr/testify/mock"
)

// BookingService is an autogenerated mock type for the BookingService type
type BookingService struct {
	mock.Mock
}

// CancelUserBooking provides a mock function with given fields: ctx, userId, bookingId
func (_m *BookingService) CancelUserBooking(ctx context.Context, userId uuid.UUID, bookingId string) (domain.BookingRequest, error) {
	ret := _m.Called(ctx, userId, bookingId)

	if len(ret) == 0 {
		panic("no return value specified for CancelUserBooking")
	}

	var r0 domain.BookingRequest
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, string) (domain.BookingRequest, error)); ok {
		return rf(ctx, userId, bookingId)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, string) domain.BookingRequest); ok {
		r0 = rf(ctx, userId, bookingId)
	} else {
		r0 = ret.Get(0).(domain.BookingRequest)
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID, string) error); ok {
		r1 = rf(ctx, userId, bookingId)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// CreateBooking provides a mock function with given fields: ctx, booking
func (_m *BookingService) CreateBooking(ctx context.Context, booking domain.BookingRequest) (domain.BookingRequest, error) {
	ret := _m.Called(ctx, booking)

	if len(ret) == 0 {
		panic("no return value specified for CreateBooking")
	}

	var r0 domain.BookingRequest
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, domain.BookingRequest) (domain.BookingRequest, error)); ok {
		return rf(ctx, booking)
	}
	if rf, ok := ret.Get(0).(func(context.Context, domain.BookingRequest) domain.BookingRequest); ok {
		r0 = rf(ctx, booking)
	} else {
		r0 = ret.Get(0).(domain.BookingRequest)
	}

	if rf, ok := ret.Get(1).(func(context.Context, domain.BookingRequest) error); ok {
		r1 = rf(ctx, booking)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// CreateRoom provides a mock function with given fields: ctx, room
func (_m *BookingService) CreateRoom(ctx context.Context, room domain.Room) (domain.Room, error) {
	ret := _m.Called(ctx, room)

	if len(ret) == 0 {
		panic("no return value specified for CreateRoom")
	}

	var r0 domain.Room
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, domain.Room) (domain.Room, error)); ok {
		return rf(ctx, room)
	}
	if rf, ok := ret.Get(0).(func(context.Context, domain.Room) domain.Room); ok {
		r0 = rf(ctx, room)
	} else {
		r0 = ret.Get(0).(domain.Room)
	}

	if rf, ok := ret.Get(1).(func(context.Context, domain.Room) error); ok {
		r1 = rf(ctx, room)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// CreateSchedule provides a mock function with given fields: ctx, roomSchedule
func (_m *BookingService) CreateSchedule(ctx context.Context, roomSchedule domain.RoomSchedule) (domain.RoomSchedule, error) {
	ret := _m.Called(ctx, roomSchedule)

	if len(ret) == 0 {
		panic("no return value specified for CreateSchedule")
	}

	var r0 domain.RoomSchedule
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, domain.RoomSchedule) (domain.RoomSchedule, error)); ok {
		return rf(ctx, roomSchedule)
	}
	if rf, ok := ret.Get(0).(func(context.Context, domain.RoomSchedule) domain.RoomSchedule); ok {
		r0 = rf(ctx, roomSchedule)
	} else {
		r0 = ret.Get(0).(domain.RoomSchedule)
	}

	if rf, ok := ret.Get(1).(func(context.Context, domain.RoomSchedule) error); ok {
		r1 = rf(ctx, roomSchedule)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetBookings provides a mock function with given fields: ctx, pagination
func (_m *BookingService) GetBookings(ctx context.Context, pagination domain.Pagination) ([]domain.BookingRequest, int, error) {
	ret := _m.Called(ctx, pagination)

	if len(ret) == 0 {
		panic("no return value specified for GetBookings")
	}

	var r0 []domain.BookingRequest
	var r1 int
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, domain.Pagination) ([]domain.BookingRequest, int, error)); ok {
		return rf(ctx, pagination)
	}
	if rf, ok := ret.Get(0).(func(context.Context, domain.Pagination) []domain.BookingRequest); ok {
		r0 = rf(ctx, pagination)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.BookingRequest)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, domain.Pagination) int); ok {
		r1 = rf(ctx, pagination)
	} else {
		r1 = ret.Get(1).(int)
	}

	if rf, ok := ret.Get(2).(func(context.Context, domain.Pagination) error); ok {
		r2 = rf(ctx, pagination)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// GetMyBookings provides a mock function with given fields: ctx, userId
func (_m *BookingService) GetMyBookings(ctx context.Context, userId uuid.UUID) ([]domain.BookingRequest, error) {
	ret := _m.Called(ctx, userId)

	if len(ret) == 0 {
		panic("no return value specified for GetMyBookings")
	}

	var r0 []domain.BookingRequest
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) ([]domain.BookingRequest, error)); ok {
		return rf(ctx, userId)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) []domain.BookingRequest); ok {
		r0 = rf(ctx, userId)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.BookingRequest)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, userId)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetRooms provides a mock function with given fields: ctx
func (_m *BookingService) GetRooms(ctx context.Context) ([]domain.Room, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetRooms")
	}

	var r0 []domain.Room
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) ([]domain.Room, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []domain.Room); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.Room)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetSlots provides a mock function with given fields: ctx, roomId, date
func (_m *BookingService) GetSlots(ctx context.Context, roomId uuid.UUID, date string) ([]domain.Slot, error) {
	ret := _m.Called(ctx, roomId, date)

	if len(ret) == 0 {
		panic("no return value specified for GetSlots")
	}

	var r0 []domain.Slot
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, string) ([]domain.Slot, error)); ok {
		return rf(ctx, roomId, date)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, string) []domain.Slot); ok {
		r0 = rf(ctx, roomId, date)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.Slot)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID, string) error); ok {
		r1 = rf(ctx, roomId, date)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Login provides a mock function with given fields: ctx, user
func (_m *BookingService) Login(ctx context.Context, user domain.User) (domain.User, error) {
	ret := _m.Called(ctx, user)

	if len(ret) == 0 {
		panic("no return value specified for Login")
	}

	var r0 domain.User
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, domain.User) (domain.User, error)); ok {
		return rf(ctx, user)
	}
	if rf, ok := ret.Get(0).(func(context.Context, domain.User) domain.User); ok {
		r0 = rf(ctx, user)
	} else {
		r0 = ret.Get(0).(domain.User)
	}

	if rf, ok := ret.Get(1).(func(context.Context, domain.User) error); ok {
		r1 = rf(ctx, user)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Register provides a mock function with given fields: ctx, user
func (_m *BookingService) Register(ctx context.Context, user domain.User) (domain.User, error) {
	ret := _m.Called(ctx, user)

	if len(ret) == 0 {
		panic("no return value specified for Register")
	}

	var r0 domain.User
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, domain.User) (domain.User, error)); ok {
		return rf(ctx, user)
	}
	if rf, ok := ret.Get(0).(func(context.Context, domain.User) domain.User); ok {
		r0 = rf(ctx, user)
	} else {
		r0 = ret.Get(0).(domain.User)
	}

	if rf, ok := ret.Get(1).(func(context.Context, domain.User) error); ok {
		r1 = rf(ctx, user)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewBookingService creates a new instance of BookingService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewBookingService(t interface {
	mock.TestingT
	Cleanup(func())
}) *BookingService {
	mock := &BookingService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
