// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	domain "avitoBooking/internal/core/domain"
	context "context"

	uuid "github.com/google/uuid"
	mock "github.com/stretchr/testify/mock"
)

// roomsService is an autogenerated mock type for the roomsService type
type roomsService struct {
	mock.Mock
}

// CreateRoom provides a mock function with given fields: ctx, room
func (_m *roomsService) CreateRoom(ctx context.Context, room domain.Room) (domain.Room, error) {
	ret := _m.Called(ctx, room)

	if len(ret) == 0 {
		panic("no return value specified for CreateRoom")
	}

	var r0 domain.Room
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, domain.Room) (domain.Room, error)); ok {
		return rf(ctx, room)
	}
	if rf, ok := ret.Get(0).(func(context.Context, domain.Room) domain.Room); ok {
		r0 = rf(ctx, room)
	} else {
		r0 = ret.Get(0).(domain.Room)
	}

	if rf, ok := ret.Get(1).(func(context.Context, domain.Room) error); ok {
		r1 = rf(ctx, room)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// CreateSchedule provides a mock function with given fields: ctx, roomSchedule
func (_m *roomsService) CreateSchedule(ctx context.Context, roomSchedule domain.RoomSchedule) (domain.RoomSchedule, error) {
	ret := _m.Called(ctx, roomSchedule)

	if len(ret) == 0 {
		panic("no return value specified for CreateSchedule")
	}

	var r0 domain.RoomSchedule
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, domain.RoomSchedule) (domain.RoomSchedule, error)); ok {
		return rf(ctx, roomSchedule)
	}
	if rf, ok := ret.Get(0).(func(context.Context, domain.RoomSchedule) domain.RoomSchedule); ok {
		r0 = rf(ctx, roomSchedule)
	} else {
		r0 = ret.Get(0).(domain.RoomSchedule)
	}

	if rf, ok := ret.Get(1).(func(context.Context, domain.RoomSchedule) error); ok {
		r1 = rf(ctx, roomSchedule)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetRooms provides a mock function with given fields: ctx
func (_m *roomsService) GetRooms(ctx context.Context) ([]domain.Room, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetRooms")
	}

	var r0 []domain.Room
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) ([]domain.Room, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []domain.Room); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.Room)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetSlots provides a mock function with given fields: ctx, roomId, date
func (_m *roomsService) GetSlots(ctx context.Context, roomId uuid.UUID, date string) ([]domain.Slot, error) {
	ret := _m.Called(ctx, roomId, date)

	if len(ret) == 0 {
		panic("no return value specified for GetSlots")
	}

	var r0 []domain.Slot
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, string) ([]domain.Slot, error)); ok {
		return rf(ctx, roomId, date)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, string) []domain.Slot); ok {
		r0 = rf(ctx, roomId, date)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.Slot)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID, string) error); ok {
		r1 = rf(ctx, roomId, date)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// newRoomsService creates a new instance of roomsService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newRoomsService(t interface {
	mock.TestingT
	Cleanup(func())
}) *roomsService {
	mock := &roomsService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
