// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	auth "avitoBooking/internal/core/auth"

	uuid "github.com/google/uuid"
	mock "github.com/stretchr/testify/mock"
)

// JwtProvider is an autogenerated mock type for the JwtProvider type
type JwtProvider struct {
	mock.Mock
}

// NewToken provides a mock function with given fields: role, userId
func (_m *JwtProvider) NewToken(role string, userId uuid.UUID) (string, error) {
	ret := _m.Called(role, userId)

	if len(ret) == 0 {
		panic("no return value specified for NewToken")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(string, uuid.UUID) (string, error)); ok {
		return rf(role, userId)
	}
	if rf, ok := ret.Get(0).(func(string, uuid.UUID) string); ok {
		r0 = rf(role, userId)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(string, uuid.UUID) error); ok {
		r1 = rf(role, userId)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ParseToken provides a mock function with given fields: tokenString
func (_m *JwtProvider) ParseToken(tokenString string) (auth.Token, error) {
	ret := _m.Called(tokenString)

	if len(ret) == 0 {
		panic("no return value specified for ParseToken")
	}

	var r0 auth.Token
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (auth.Token, error)); ok {
		return rf(tokenString)
	}
	if rf, ok := ret.Get(0).(func(string) auth.Token); ok {
		r0 = rf(tokenString)
	} else {
		r0 = ret.Get(0).(auth.Token)
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(tokenString)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewJwtProvider creates a new instance of JwtProvider. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewJwtProvider(t interface {
	mock.TestingT
	Cleanup(func())
}) *JwtProvider {
	mock := &JwtProvider{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
